# GitHub Pages Configuration
# This enables the custom layout for all markdown files

# Theme (using minimal for GitHub Pages compatibility)
theme: jekyll-theme-minimal

# Markdown processor
markdown: kramdown

# Set the layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Enable relative links
relative_links:
  enabled: true
  collections: false

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings

# Titles from headings
titles_from_headings:
  enabled: true
  strip_title: false
  collections: false

# Optional front matter
optional_front_matter:
  enabled: true

# README index
readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: false
